#-*- coding: utf-8 -*-
puts "deleting Position and SubPosition ..."
Position.delete_all
SubPosition.delete_all
ActiveRecord::Base.connection.execute "ALTER TABLE positions AUTO_INCREMENT = 1"
ActiveRecord::Base.connection.execute "ALTER TABLE sub_positions AUTO_INCREMENT = 1"

puts "init Position and SubPosition ..."
position = Position.create(:name=>"客户服务")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"客服总监", :position_id=>position.id)
SubPosition.create(:name=>"客服经理/客服主管", :position_id=>position.id)
SubPosition.create(:name=>"客服专员/客服助理", :position_id=>position.id)
SubPosition.create(:name=>"客户关系管理", :position_id=>position.id)
SubPosition.create(:name=>"客服文员", :position_id=>position.id)
SubPosition.create(:name=>"售前客服", :position_id=>position.id)
SubPosition.create(:name=>"售后客服", :position_id=>position.id)
SubPosition.create(:name=>"客户/热线咨询", :position_id=>position.id)
SubPosition.create(:name=>"技术支持/客户培训", :position_id=>position.id)
SubPosition.create(:name=>"客户服务其它", :position_id=>position.id)

position = Position.create(:name=>"经营/管理")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"技术经理/项目经理", :position_id=>position.id)
SubPosition.create(:name=>"企管部经理", :position_id=>position.id)
SubPosition.create(:name=>"投资管理", :position_id=>position.id)
SubPosition.create(:name=>"部门经理", :position_id=>position.id)
SubPosition.create(:name=>"厂长/副厂长", :position_id=>position.id)
SubPosition.create(:name=>"副总经理/营运总裁", :position_id=>position.id)
SubPosition.create(:name=>"企业策划(企划)", :position_id=>position.id)
SubPosition.create(:name=>"总经理助理/秘书", :position_id=>position.id)
SubPosition.create(:name=>"(正/副)总裁/总经理", :position_id=>position.id)
SubPosition.create(:name=>"经营/管理其它", :position_id=>position.id)

position = Position.create(:name=>"行政/人事/培训")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"薪酬福利经理/主管", :position_id=>position.id)
SubPosition.create(:name=>"绩效考核经理/主管", :position_id=>position.id)
SubPosition.create(:name=>"招聘专员/招聘助理", :position_id=>position.id)
SubPosition.create(:name=>"行政文员", :position_id=>position.id)
SubPosition.create(:name=>"培训部经理", :position_id=>position.id)
SubPosition.create(:name=>"培训专员/培训助理", :position_id=>position.id)
SubPosition.create(:name=>"企业文化/工会", :position_id=>position.id)
SubPosition.create(:name=>"行政/人事主管", :position_id=>position.id)
SubPosition.create(:name=>"行政/人事专员", :position_id=>position.id)
SubPosition.create(:name=>"行政/人力资源经理", :position_id=>position.id)
SubPosition.create(:name=>"行政/人力资源总裁", :position_id=>position.id)
SubPosition.create(:name=>"行政/人事/培训其它", :position_id=>position.id)

position = Position.create(:name=>"市场/营销")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"市场总监", :position_id=>position.id)
SubPosition.create(:name=>"市场经理/市场主管", :position_id=>position.id)
SubPosition.create(:name=>"市场专员/市场助理", :position_id=>position.id)
SubPosition.create(:name=>"市场调研与分析", :position_id=>position.id)
SubPosition.create(:name=>"产品经理/品牌经理", :position_id=>position.id)
SubPosition.create(:name=>"产品专员/品牌专员", :position_id=>position.id)
SubPosition.create(:name=>"促销经理/促销主管", :position_id=>position.id)
SubPosition.create(:name=>"市场企划经理/主管", :position_id=>position.id)
SubPosition.create(:name=>"市场企划专员", :position_id=>position.id)
SubPosition.create(:name=>"广告策划/文案", :position_id=>position.id)
SubPosition.create(:name=>"信息员/联络员", :position_id=>position.id)
SubPosition.create(:name=>"公关媒介经理/主管", :position_id=>position.id)
SubPosition.create(:name=>"公关媒介专员", :position_id=>position.id)
SubPosition.create(:name=>"市场渠道", :position_id=>position.id)
SubPosition.create(:name=>"市场/行销策划", :position_id=>position.id)
SubPosition.create(:name=>"市场/营销其它", :position_id=>position.id)

position = Position.create(:name=>"机械技术/技工")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"报验员", :position_id=>position.id)
SubPosition.create(:name=>"印刷工手工艺品制造", :position_id=>position.id)
SubPosition.create(:name=>"机械操作工", :position_id=>position.id)
SubPosition.create(:name=>"电器维修工", :position_id=>position.id)
SubPosition.create(:name=>"汽车修理工", :position_id=>position.id)
SubPosition.create(:name=>"铸造/电镀", :position_id=>position.id)
SubPosition.create(:name=>"派送员/保洁工", :position_id=>position.id)
SubPosition.create(:name=>"裁剪车缝熨烫", :position_id=>position.id)
SubPosition.create(:name=>"叉车工", :position_id=>position.id)
SubPosition.create(:name=>"空调/电梯/锅炉工", :position_id=>position.id)
SubPosition.create(:name=>"模具工", :position_id=>position.id)
SubPosition.create(:name=>"车/磨/铣/冲/锣工", :position_id=>position.id)
SubPosition.create(:name=>"电焊工", :position_id=>position.id)
SubPosition.create(:name=>"机修工钣金工", :position_id=>position.id)
SubPosition.create(:name=>"钳工", :position_id=>position.id)
SubPosition.create(:name=>"机械专业人员", :position_id=>position.id)
SubPosition.create(:name=>"机修工程师", :position_id=>position.id)
SubPosition.create(:name=>"设备机械维修", :position_id=>position.id)
SubPosition.create(:name=>"各种车辆/飞行器", :position_id=>position.id)
SubPosition.create(:name=>"机械设计", :position_id=>position.id)
SubPosition.create(:name=>"机电工程师", :position_id=>position.id)
SubPosition.create(:name=>"模具设计工程师", :position_id=>position.id)
SubPosition.create(:name=>"机械工程师", :position_id=>position.id)
SubPosition.create(:name=>"机械技术/技工其它", :position_id=>position.id)

position = Position.create(:name=>"文职/秘书")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"编辑记者", :position_id=>position.id)
SubPosition.create(:name=>"前台/接待/礼仪", :position_id=>position.id)
SubPosition.create(:name=>"资料文档编辑/撰写", :position_id=>position.id)
SubPosition.create(:name=>"档案/图文情报/资料", :position_id=>position.id)
SubPosition.create(:name=>"文员/电脑打字员", :position_id=>position.id)
SubPosition.create(:name=>"总经理秘书/高级助理", :position_id=>position.id)
SubPosition.create(:name=>"文职/秘书其它", :position_id=>position.id)

position = Position.create(:name=>"设计/广告/策划")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"配件设计", :position_id=>position.id)
SubPosition.create(:name=>"会展/展览设计", :position_id=>position.id)
SubPosition.create(:name=>"机械设计", :position_id=>position.id)
SubPosition.create(:name=>"建筑设计", :position_id=>position.id)
SubPosition.create(:name=>"电脑制版", :position_id=>position.id)
SubPosition.create(:name=>"家具设计", :position_id=>position.id)
SubPosition.create(:name=>"电脑绘图", :position_id=>position.id)
SubPosition.create(:name=>"服装/纺织品设计", :position_id=>position.id)
SubPosition.create(:name=>"设计/广告/策划其它", :position_id=>position.id)

position = Position.create(:name=>"酒店/餐饮/旅游")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"宾馆/酒店经理", :position_id=>position.id)
SubPosition.create(:name=>"娱乐/餐饮管理", :position_id=>position.id)
SubPosition.create(:name=>"大堂经理/副理", :position_id=>position.id)
SubPosition.create(:name=>"前台接待/收银员", :position_id=>position.id)
SubPosition.create(:name=>"总机话务员", :position_id=>position.id)
SubPosition.create(:name=>"服务员", :position_id=>position.id)
SubPosition.create(:name=>"楼层领班", :position_id=>position.id)
SubPosition.create(:name=>"保洁员", :position_id=>position.id)
SubPosition.create(:name=>"酒店/餐饮/旅游/其它", :position_id=>position.id)

position = Position.create(:name=>"财务/审(统)计")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"稽核员", :position_id=>position.id)
SubPosition.create(:name=>"审计/审计注册师", :position_id=>position.id)
SubPosition.create(:name=>"统计", :position_id=>position.id)
SubPosition.create(:name=>"出纳/收银员", :position_id=>position.id)
SubPosition.create(:name=>"会计", :position_id=>position.id)
SubPosition.create(:name=>"财务/审(统)计其它", :position_id=>position.id)

position = Position.create(:name=>"贸易/采购")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"外贸经理/主管", :position_id=>position.id)
SubPosition.create(:name=>"外贸/外贸操作员", :position_id=>position.id)
SubPosition.create(:name=>"外贸/外贸业务员", :position_id=>position.id)
SubPosition.create(:name=>"外贸电子商务", :position_id=>position.id)
SubPosition.create(:name=>"翻译", :position_id=>position.id)
SubPosition.create(:name=>"外贸文员", :position_id=>position.id)
SubPosition.create(:name=>"外贸验货", :position_id=>position.id)
SubPosition.create(:name=>"采购员", :position_id=>position.id)
SubPosition.create(:name=>"跟单员", :position_id=>position.id)
SubPosition.create(:name=>"报检员", :position_id=>position.id)
SubPosition.create(:name=>"仓管/仓库管理", :position_id=>position.id)
SubPosition.create(:name=>"贸易/采购其它", :position_id=>position.id)

position = Position.create(:name=>"化工/环境")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"有机化工", :position_id=>position.id)
SubPosition.create(:name=>"无机化工", :position_id=>position.id)
SubPosition.create(:name=>"精细化工", :position_id=>position.id)
SubPosition.create(:name=>"高分子化工", :position_id=>position.id)
SubPosition.create(:name=>"化工技术", :position_id=>position.id)
SubPosition.create(:name=>"环保", :position_id=>position.id)
SubPosition.create(:name=>"化工/环境其它", :position_id=>position.id)

position = Position.create(:name=>"生产制造/质量控制")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"厂长/副厂长", :position_id=>position.id)
SubPosition.create(:name=>"生产管理", :position_id=>position.id)
SubPosition.create(:name=>"品质管理", :position_id=>position.id)
SubPosition.create(:name=>"仓库管理", :position_id=>position.id)
SubPosition.create(:name=>"工程管理", :position_id=>position.id)
SubPosition.create(:name=>"物料管理", :position_id=>position.id)
SubPosition.create(:name=>"设备管理", :position_id=>position.id)
SubPosition.create(:name=>"采购管理", :position_id=>position.id)
SubPosition.create(:name=>"计划员", :position_id=>position.id)
SubPosition.create(:name=>"产品开发", :position_id=>position.id)
SubPosition.create(:name=>"生产制造/质量控制其它", :position_id=>position.id)

position = Position.create(:name=>"销售/业务")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"销售总监", :position_id=>position.id)
SubPosition.create(:name=>"销售经理/销售主管", :position_id=>position.id)
SubPosition.create(:name=>"业务员/销售代表", :position_id=>position.id)
SubPosition.create(:name=>"电话销售", :position_id=>position.id)
SubPosition.create(:name=>"医药代表", :position_id=>position.id)
SubPosition.create(:name=>"业务拓展(BD)经理", :position_id=>position.id)
SubPosition.create(:name=>"医疗器械销售", :position_id=>position.id)
SubPosition.create(:name=>"渠道代表", :position_id=>position.id)
SubPosition.create(:name=>"销售/业务其它", :position_id=>position.id)

position = Position.create(:name=>"法律/法务")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"律师", :position_id=>position.id)
SubPosition.create(:name=>"法律顾问", :position_id=>position.id)
SubPosition.create(:name=>"法务人员", :position_id=>position.id)
SubPosition.create(:name=>"法务助理", :position_id=>position.id)
SubPosition.create(:name=>"书记员", :position_id=>position.id)
SubPosition.create(:name=>"律师助理", :position_id=>position.id)
SubPosition.create(:name=>"知识产权/专业顾问", :position_id=>position.id)
SubPosition.create(:name=>"法律/法务其它", :position_id=>position.id)

position = Position.create(:name=>"金融/经济专业人")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"证券.外汇.期货经理", :position_id=>position.id)
SubPosition.create(:name=>"投资管理/投资顾问", :position_id=>position.id)
SubPosition.create(:name=>"客户经理", :position_id=>position.id)
SubPosition.create(:name=>"行长/副行长", :position_id=>position.id)
SubPosition.create(:name=>"拍卖师", :position_id=>position.id)
SubPosition.create(:name=>"保险内勤", :position_id=>position.id)
SubPosition.create(:name=>"保险代理人", :position_id=>position.id)
SubPosition.create(:name=>"金融/经济专业人其它", :position_id=>position.id)

position = Position.create(:name=>"建筑/房地产/物业管理")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"房地产经纪人", :position_id=>position.id)
SubPosition.create(:name=>"房地产销售", :position_id=>position.id)
SubPosition.create(:name=>"房地产营销策划师", :position_id=>position.id)
SubPosition.create(:name=>"房地产评估/交易", :position_id=>position.id)
SubPosition.create(:name=>"房地产开发/策划", :position_id=>position.id)
SubPosition.create(:name=>"物业管理/顾问/维修", :position_id=>position.id)
SubPosition.create(:name=>"保险代理人", :position_id=>position.id)
SubPosition.create(:name=>"建筑/房地产/物业管理其它", :position_id=>position.id)

position = Position.create(:name=>"外语翻译")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"英语", :position_id=>position.id)
SubPosition.create(:name=>"阿拉伯语", :position_id=>position.id)
SubPosition.create(:name=>"日语", :position_id=>position.id)
SubPosition.create(:name=>"韩语", :position_id=>position.id)
SubPosition.create(:name=>"俄语", :position_id=>position.id)
SubPosition.create(:name=>"西班牙语", :position_id=>position.id)
SubPosition.create(:name=>"法语", :position_id=>position.id)
SubPosition.create(:name=>"德语", :position_id=>position.id)
SubPosition.create(:name=>"巴基斯坦语", :position_id=>position.id)
SubPosition.create(:name=>"外语翻译其它", :position_id=>position.id)

position = Position.create(:name=>"医疗/卫生/护理")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"中医医师", :position_id=>position.id)
SubPosition.create(:name=>"西医医师", :position_id=>position.id)
SubPosition.create(:name=>"外科医师", :position_id=>position.id)
SubPosition.create(:name=>"内科医师", :position_id=>position.id)
SubPosition.create(:name=>"心理医生", :position_id=>position.id)
SubPosition.create(:name=>"药剂师", :position_id=>position.id)
SubPosition.create(:name=>"足浴技师", :position_id=>position.id)
SubPosition.create(:name=>"医疗/卫生/护理其它", :position_id=>position.id)

position = Position.create(:name=>"文学/教育/体育")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"教学/教务管理人员", :position_id=>position.id)
SubPosition.create(:name=>"小学教师", :position_id=>position.id)
SubPosition.create(:name=>"中等教育", :position_id=>position.id)
SubPosition.create(:name=>"高等教育", :position_id=>position.id)
SubPosition.create(:name=>"体育", :position_id=>position.id)
SubPosition.create(:name=>"家教", :position_id=>position.id)
SubPosition.create(:name=>"助教", :position_id=>position.id)
SubPosition.create(:name=>"文学/教育/体育其它", :position_id=>position.id)

position = Position.create(:name=>"计算机/IT")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"技术总监", :position_id=>position.id)
SubPosition.create(:name=>"技术经理/技术主管", :position_id=>position.id)
SubPosition.create(:name=>"技术专员", :position_id=>position.id)
SubPosition.create(:name=>"产品经理", :position_id=>position.id)
SubPosition.create(:name=>"系统分析员", :position_id=>position.id)
SubPosition.create(:name=>"软件工程师", :position_id=>position.id)
SubPosition.create(:name=>"网络工程师", :position_id=>position.id)
SubPosition.create(:name=>"计算机/IT其它", :position_id=>position.id)

position = Position.create(:name=>"电子商务/淘宝")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"电子商务运营总监", :position_id=>position.id)
SubPosition.create(:name=>"电子商务主管", :position_id=>position.id)
SubPosition.create(:name=>"英文电子商务", :position_id=>position.id)
SubPosition.create(:name=>"中文电子商务", :position_id=>position.id)
SubPosition.create(:name=>"淘宝客服/美工/拍照", :position_id=>position.id)
SubPosition.create(:name=>"淘宝配货", :position_id=>position.id)
SubPosition.create(:name=>"图片处理", :position_id=>position.id)
SubPosition.create(:name=>"电子商务/淘宝其它", :position_id=>position.id)

position = Position.create(:name=>"货运/快递/物流")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"司机/驾驶员", :position_id=>position.id)
SubPosition.create(:name=>"仓库/仓库管理", :position_id=>position.id)
SubPosition.create(:name=>"货运操作", :position_id=>position.id)
SubPosition.create(:name=>"货运代理", :position_id=>position.id)
SubPosition.create(:name=>"海运/空运/陆运人员", :position_id=>position.id)
SubPosition.create(:name=>"快递员/速递员", :position_id=>position.id)
SubPosition.create(:name=>"图片处理", :position_id=>position.id)
SubPosition.create(:name=>"货运/快递/物流其它", :position_id=>position.id)

position = Position.create(:name=>"店面/超市/商业零售")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"店长/店面管理", :position_id=>position.id)
SubPosition.create(:name=>"营业员/店面销售", :position_id=>position.id)
SubPosition.create(:name=>"店长助理", :position_id=>position.id)
SubPosition.create(:name=>"仓管员", :position_id=>position.id)
SubPosition.create(:name=>"储备干部", :position_id=>position.id)
SubPosition.create(:name=>"店面/超市/商业零售其它", :position_id=>position.id)

position = Position.create(:name=>"汽车销售与服务")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"汽车销售顾问", :position_id=>position.id)
SubPosition.create(:name=>"汽车服务顾问", :position_id=>position.id)
SubPosition.create(:name=>"汽车保险专员", :position_id=>position.id)
SubPosition.create(:name=>"汽车事故专员", :position_id=>position.id)
SubPosition.create(:name=>"洗车工", :position_id=>position.id)
SubPosition.create(:name=>"汽车销售与服务其它", :position_id=>position.id)

position = Position.create(:name=>"文体/影视/媒体")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"广播电视/文化艺人", :position_id=>position.id)
SubPosition.create(:name=>"作家/撰稿人", :position_id=>position.id)
SubPosition.create(:name=>"总编/副总编", :position_id=>position.id)
SubPosition.create(:name=>"校对/录入", :position_id=>position.id)
SubPosition.create(:name=>"录音/音效师", :position_id=>position.id)
SubPosition.create(:name=>"文体/影视/媒体其它", :position_id=>position.id)

position = Position.create(:name=>"其它")
SubPosition.create(:name=>"不限", :position_id=>position.id)
SubPosition.create(:name=>"其它", :position_id=>position.id)
























